# Generated by Django 3.0.5 on 2020-05-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogTable',
            new_name='Blog',
        ),
    ]
